- js/lib/cli.js
- python/jsbeautifier/__init__.py
> rewrite file only when file data changed

- README.md
- js/lib/beautify-html.js
- js/lib/cli.js
This will put attributes on new lines if configured
-------
```html
<div    {{something}} attr1="123" data-attr2="hello    t here" {{#test}}disabled {{/test}}
>
This is some content    </div>
<div oneattr="one">
Some content
</div>
```
```json
{
"wrap_attributes": true,
"wrap_indent": 8,
"wrap_line_length": 144
}
```
```html
<div {{something}}
attr1="123"
data-attr2="hello    t here"
{{#test}}disabled
{{/test}}>
This is some content</div>
<div oneattr="one">
Some content
</div>
```
> Add wrap_attributes and wrap_indent config parameters for HTML

- index.html
Creates a GUI option to go from:
```html
<html>
<head></head>
<body></body>
</html>
```
To:
```html
<html>
<head></head>
<body></body>
</html>
```
I would like to also add an option to go to:
```html
<html>
<head></head>
<body></body>
</html>
```
But maybe later, seeing as the underlying engine does not seem to support it (?).
> Add GUI support for `--indent-inner-html`.

- js/lib/beautify.js
- js/test/beautify-javascript-tests.js
- python/jsbeautifier/__init__.py
- python/jsbeautifier/tests/testjsbeautifier.py
- test/data/javascript.js
I found this bug while parsing things like:
```
for (index in [1,2,3]) /^salign$/i.test('salign')
```
(from https://github.com/rspivak/slimit/issues/54)
Before the fix, you get:
```
for (index in [1, 2, 3]) / ^ salign$ / i.test('salign')
```
The regular expression is not detected.
With this fix, the regular expression literal is kept as-is:
```
>>> import jsbeautifier
>>> print jsbeautifier.beautify("for (index in [1,2,3]) /^salign$/i.test('salign')")
for (index in [1,2,3]) /^salign$/i.test('salign')
>>> 
```
> Fix tokenizer's bracket pairs' open stack

- js/test/node-beautify-tests.js
Since the legacy and new names point to the same object,
there is no need to run through all the tests separately
> Remove unnecessary legacy tests

- js/lib/beautify.js
- js/test/beautify-javascript-tests.js
- python/jsbeautifier/__init__.py
- python/jsbeautifier/tests/testjsbeautifier.py
- test/data/javascript.js
Should resolve #685.
Although decorators are just a [proposal](https://github.com/wycats/javascript-decorators), they are already implemented in Babel, and used in some frameworks. Currently, js-beautifier adds a line break after the unexpected "@" character in the decorator invocation. With this commit, "@" will be an accepted identifier leader, like A-Z, a-z, $, and _.
Tests included and passing locally.
> Resolves #685: Permit ES7 decorators.

- index.html
I have had enough of this typo which I have seen for years now.
> Fix typo in the example javascript code of index.html

- js/lib/beautify-html.js
Without this fix `is_whitespace` only ever checks the first character. Called when the first token is text content; If that token has leading whitespace the whole token is ignored (content loss). Bug not present in python implementation.
> is_whitespace for loop incrementing wrong variable

- js/lib/beautify-html.js
- js/test/beautify-html-tests.js
- test/data/html.js
Solves the problem shown in the issue.
A newline will only be placed before an `{{else}}` tag when it's corresponding `{{#f}}` tag is on a separate line.
My method for finding whether or not an `{{#if}}` tag is on the same line is a bit lame/naive (checking back on previously-output tokens) and could be improved by someone who knows the code base better
N.B only fixed JS version. Python not touched
> Resolve #784 Handlebars {{else}} tag not given a newline

- js/lib/beautify.js
- js/test/beautify-javascript-tests.js
- python/jsbeautifier/__init__.py
- python/jsbeautifier/tests/testjsbeautifier.py
- test/data/javascript.js
- test/template/python-javascript.mustache
I had to update some of the decode tests - they no longer made sense once wrapped in the second part of the test and were failing. Let me know if this works for you.
> Resolving #810: ES6 Object Literal Shorthand Detection

- package.json
We use `js-beautify` internally, as part of [`standard`](http://standardjs.com/). Our users get this warning whenever they `npm install standard`:
```
npm WARN prefer global js-beautify@1.5.10 should be installed with -g
```
It's no longer a best-practice to use `preferGlobal` for npm packages that merely contain a command line program. The command line program should be *the only* way to use the package.
Thoughts?
> package.json: Remove "preferGlobal" option

- js/lib/cli.js
- js/test/shell-smoke-test.sh
- python/jsbeautifier/__init__.py
- python/jsbeautifier/tests/shell-smoke-test.sh
> Read piped input by default

- README.md
- index.html
- js/lib/beautify.js
- js/test/generated/beautify-javascript-tests.js
- python/jsbeautifier/__init__.py
- python/jsbeautifier/tests/generated/tests.py
- test/data/javascript/tests.js
Fixes #114 
Fixes #315 
Fixes #370
Fixes #382
> Destructuring, importing, and short objects

- js/lib/cli.js
I wasn't able to use the new `collapse-preserve-inline` using the npm module, so I decided to take a look and found out it was missing.
> Add missing 'collapse-preserve-inline' option to js module

- .gitignore
- js/lib/beautify.js
- js/lib/cli.js
- js/test/generated/beautify-javascript-tests.js
- python/jsbeautifier/__init__.py
- python/jsbeautifier/tests/generated/tests.py
- test/data/javascript/inputlib.js
- test/data/javascript/node.mustache
- test/data/javascript/python.mustache
- test/data/javascript/tests.js
- Added verification of operator_position option.  Throws error if
invalid.
- Possible operator_position options are:
1) undefined (use default behavior)
2) 'before_newline'
3) 'after_newline'
4) 'preserve_newline'
5) 'remove_newline'
- Moved some code around in handle_operator in order to separate
conflicting logic when handling operators.
- Modified allow_wrap_or_preserved_newline to handle operator
preserved newlines as well.
- Fixed a few boolean variable assignments within if statements.
Though not always the case, the expression within the if can
be assigned directly to the variable
- Added -> built tests
- Within the tests, added an 'inputlib.js' file which holds common
input arrays.  This was necessary due to the matrices not working
cleanly with default behavior.
- It is worth …
> first draft of operator_position functionality

- js/test/generated/beautify-javascript-tests.js
- python/jsbeautifier/__init__.py
- python/jsbeautifier/tests/generated/tests.py
- test/data/javascript/tests.js
Now it is the same as the JS list:
js/lib/beautify.js:1746
This caused operations like 'a -= 2;' to be changed to
'a - = 2;', which breaks
> Fix incomplete list of non-positionable operators (python lib)

- python/jsbeautifier/__init__.py
The current version of python jsbeautifier prints out on the stdout
unpacking errors. For example:
```
In [1]: import jsbeautifier
In [2]: s =
"eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};while(c--){if(k[c]){p=p.replace(new
RegExp('\\\\b'+e(c)+'\\\\b','g'),k[c])}}return p}('L
J=\\'%D%e%7%a%3%p%4%1%4%B%p%0%h%m%4%0%H%4%n%K%6%r%6%e%7%a%3%p%4%m%I%8%f%o%5%7%4%3%2%5%1%6%a%0%v%7%2%2%c%3%0%e%v%0%5%6%j%b%0%9%k%i%8%u%8%g%r%6%a%1%7%2%2%c%3%0%t%5%6%j%b%0%9%1%h%1%k%5%6%r%3%z%6%4%2%a%d%7%2%2%c%3%0%t%5%6%j%b%0%9%i%1%A%1%4%a%o%0%1%w%1%f%6%b%e%0%s%8%8%g%3%f%1%k%4%B%p%0%2%f%1%5%6%r%3%z%6%4%2%a%d%7%2%2%c%3%0%t%5%6%j%b%0%9%1%h%h%1%m%o%5%9%0%f%3%5%0%9%m%1%F%F%1%C%7%2%2%c%3%0%t%5%6%j%b%0%9%i%8%g%u%1%8%g%g%9%2%7%o%E%0%5%4%d%7%2%2 …
```
> don't print unpacking errors on stdout (python)

- js/lib/cli.js
Starting from node 6.0.0, the argument to `path.dirname` must be a string. Previously, `path.dirname(undefined)` returns `'.'`, but now it throws an error. For details, compare
https://nodejs.org/docs/latest-v5.x/api/path.html#path_path_dirname_p and https://nodejs.org/docs/latest-v6.x/api/path.html#path_path_dirname_path.
Also added missing newline at the end of file.
Fixes #933.
> cli.js: Make directory of outfile only if outfile is truthy

- js/lib/beautify-html.js
Example:
```html
<中文></中文>
```
Yes, this is not valid HTML according to the spec, but this commit makes the beautifier more robust against possible errors.
> Fix errors being thrown on non-Latin tag characters

- js/lib/beautify-html.js
- js/test/generated/beautify-html-tests.js
- test/data/html/tests.js
Right now
```html
<!DOCTYPE html><html><head><title>Article Title</title></head><body><h1>My</h1></body></html>
```
is beautified as
```html
<!DOCTYPE html>
<html>
<head>
<title>Article Title</title>
</head>
<body>
<h1>My</h1></body>
</html>
```
`h1` (and all other heading elements) are block-level elements.
For further information, `git blame` shows that the elements were added in 34f59337ffdfaadcddcd9422afc135c526d67620 which intended to add the inline elements only.
> Remove headings from inline element list

- README.md
- js/lib/beautify-html.js
- js/test/generated/beautify-html-tests.js
- test/data/html/tests.js
This adds a new option `"force-all"` for `"wrap_attributes"`.
- if there is just one attribute, it is not wrapped (like `"wrap_attributes": "force"`
- if there is more than one attribute, each of them has it's own line
- if attributes are wrapped, the ending part of the tag (`>` or `/>`) is in its own line
For example:
``` html
<a
accesskey="l"
class="link link-blue"
href="https://github.com/beautify-web/js-beautify/"
>
Link to a great <strong class="link-emphasis">project</strong>
</a>
```
We use this formatting style because
- all attributes are aligned without losing the indent from nesting level like with `force-aligned`
- attributes can be easily sorted (we use alphabetical sorting for attributes, would be great to implement that in js-beautify as well)
- the ending part of the tag …
> New option "force-expand-multiline" for "wrap_attributes"

- README.md
- js/lib/beautify-html.js
- js/lib/cli.js
- js/test/generated/beautify-html-tests.js
- test/data/html/tests.js
This fixes #906
The issue is that `unformatted` config is applied to following 3 places:
* newline before the element
* content of the element
* newline after the element
while it's useful for inline elements, when one want to disable formatting only the content of the content, keeping newlines before/after it, the config cannot be used.
I added new `content_unformatted` config, that does only "content of the element" part.
if `content_unformatted` one add "style" and "script" to this, their content is not formatted, while they still have newlines before/after them.
config file:
```
{
"content_unformatted": [ "script", "style" ]
}
```
output
```
$ node ./js/bin/html-beautify.js   --config ~/Desktop/conf ~/Desktop/b.html
<body>
<h1>Heading</h1>
<script>var formatMe = function() { return …
```
> Add content_unformatted config to avoid formatting content of an element (fix #906)

- README.md
- js/lib/cli.js
fixes #1047
- update cli options with exact output from `$ js-beautify --help`
- add missing json defaults found in the CLI
- reorder json defaults to correspond with CLI output
- remove 'keep_function_indentation' from documentation since it is unused
- remove html beautifier specific defaults (updating that section is out of
scope for this commit)
- separate defaults exposed by the cli and those which aren't
- reword the compatibility notice as a result of the default separation
> Update js-beautify CLI options in README

- index.html
I noticed that "Preserve inline braces/code blocks?" label was ticking "Keep array indentation?" checkbox
> Fix label checking incorrect box when clicked

- .npmignore
By ignoring everything at the start of the npmignore and then excluding the files you actually need, you can reduce your node_modules foodprint.
The difference:
| What | Current size | New size | Difference |
|-----:|:--------:|:-----:|:----:|
|node_modules| 2.18 MB | 1.57 MB | 38.85% |
| js-beautify folder | 1.27 MB | 674 KB | 46.93% |
| zipped | 656 KB | 416 KB | 36.58% |
If js-beautify would be downloaded 1.3 milion times in the month after this is released, it would save about 312 GB of traffic due to the smaller zip size.
> Don't publish unnessessary files

- js/lib/beautify.js
- js/src/javascript/beautifier.js
- js/test/generated/beautify-javascript-tests.js
- python/jsbeautifier/javascript/beautifier.py
- python/jsbeautifier/tests/generated/tests.py
- test/data/javascript/tests.js
Adds whitespace between `async` and an arrow function:
*Input*
`async() => {}`
*Output*
`async () => {}`
Addresses #896 and #1187 and is a continuation of #977
> Whitespace between async and arrow function

- js/lib/beautify.js
- js/lib/cli.js
- js/src/javascript/beautifier.js
- js/test/shell-smoke-test.sh
- python/jsbeautifier/javascript/beautifier.py
- python/jsbeautifier/tests/shell-smoke-test.sh
Per the discussion of https://github.com/beautify-web/js-beautify/pull/1058, the `brace_style` option has been made more inclusive. Also 3 shell tests have been added.
* Accepts `expand,collapse,preserve-inline` as `collapse,preserve-inline`
* Accepts `preserve-inline` as `collapse,preserve-inline` (uses the default `brace_style` `collapse`+ user specified `preserve-inline`)
* Accepts `preserve-inline,collapse` as `preserve-inline`
* Rejects `invalid,preserve-line,collapse` as invalid
Whereas in the previous version these would all reject as invalid.
> Made brace_style option more inclusive

- js/lib/beautify-css.js
- js/src/css/beautifier.js
- js/test/generated/beautify-css-tests.js
- python/cssbeautifier/css/beautifier.py
- python/cssbeautifier/tests/generated/tests.py
- test/data/css/tests.js
fixes #1273
Before:
```css
a {
color: blue!important;
}
a {
color: blue !important;
}
a {
color: blue          !important;
}
```
After:
```css
a {
color: blue !important;
}
```
> Whitespace before '!important'

- python/jsbeautifier/__init__.py
- python/jsbeautifier/tests/shell-smoke-test.sh
Missing comma in the array of long command line options passed to getopt
causes options --eol and --outfile to either be handled incorrectly or
not recognized at all.
> js-beautify: fix handling for --eol and --outfile

- tools/generate-changelog.sh
Closes issue [1314](https://github.com/beautify-web/js-beautify/issues/1314).
Successfully tested locally (README was identical before and after running).
> Add support for GNU Sort being named `sort`

- python/jsbeautifier/__init__.py
- python/jsbeautifier/tests/shell-smoke-test.sh
- All command line options use dashes as separators and not underscores.
Hence fix --space_after_anon_function and --end_with_newline in
usage().
- Add --comma-first and --operator-position to usage information.
- Fix few whitespace inconsistencies.
- Do not list <outfile> as standalone argument.  It has to be specified
as argument for the --outfile command line option.
- Properly import sanitizeOperatorPosition to validate
--operator-position option argument.
- Re-word beautify_file() exception text, as only one file can be
specified as command argument.
> js-beautify: fix usage information

- js/lib/beautify-css.js
- js/src/css/beautifier.js
- js/test/generated/beautify-css-tests.js
- test/data/css/node.mustache
Change-Id: I91fa77493eafb9de820eba802529dcf84ddd0170
See issue in:  https://github.com/beautify-web/js-beautify/issues/1156.
If "(" is detected, and it does not run in the eatString(')') block, parenLevel should always add 1.
> issue-1156:fixed line break in mixins after background url

- python/css-beautify
- python/cssbeautifier/__init__.py
This adds a command line tool for the python cssbeautifier.  It is based
on and re-uses as much code as possible from the js-beautify tool.
Long command line options make it possible to control all currently
implemented options in the CSS Beautifier.  Short command line options
are only supported for options that are identical to those of the
js-beautify tool.
Note that there is an inconsistency between the two tools caused by the
different default for the preserve_newlines option - True for
jsbeautifier and False for cssbeautifier, hence different command line
options --disable-preserve-newlines vs. --preserve-newlines.
> css-beautify: python cssbeautifier cli

- js/lib/beautify.js
- js/src/javascript/beautifier.js
- js/test/generated/beautify-javascript-tests.js
- python/jsbeautifier/javascript/beautifier.py
- python/jsbeautifier/tests/generated/tests.py
- test/data/javascript/tests.js
Resolves #1283
**What was done:**
- Adapted function print_newline to restore mode if last_test was operator ++ or --
- Added corresponding test.
**Example of behavior:**
```js
// == Input ==
{this.foo++
bar}
// == Expected Output ==
{
this.foo++
bar
}
```
> 1283 - Javascript ++ Operator Gets Wrong Indentation

- README.md
- js/lib/beautify-html.js
- js/lib/cli.js
- js/src/html/beautifier.js
- js/test/generated/beautify-html-tests.js
- test/data/html/node.mustache
- test/data/html/tests.js
- tools/template/beautify-html.begin.js
Fixes https://github.com/beautify-web/js-beautify/issues/1033
Replaces concept of `unformatted` tags with `inline` tags, which are not wrapped. Previous `unformatted` functionality moved to `content_unformatted` tags. This allows us to format the attributes of inline tags correctly.
> Format inline HTML tags

- js/src/core/tokenizer.js
- js/src/html/beautifier.js
- js/src/html/tokenizer.js
- js/test/generated/beautify-html-tests.js
- js/test/generated/beautify-javascript-tests.js
- python/jsbeautifier/core/tokenizer.py
- python/jsbeautifier/tests/generated/tests.py
- test/data/html/tests.js
- test/data/javascript/tests.js
Fixes #1496
@astronomersiva this converts the &nbsp character into a space. I think this is a decent fix, because people generally should be using `&nbsp;` in html. Let me know if you disagree.
> Fixed whitespace detection issue with tests

- js/src/core/options.js
- js/src/css/beautifier.js
- js/src/html/beautifier.js
- js/src/javascript/beautifier.js
- js/test/generated/beautify-css-tests.js
- js/test/generated/beautify-html-tests.js
- js/test/generated/beautify-javascript-tests.js
- python/cssbeautifier/css/beautifier.py
- python/cssbeautifier/tests/generated/tests.py
- python/jsbeautifier/core/options.py
- python/jsbeautifier/javascript/beautifier.py
- python/jsbeautifier/tests/generated/tests.py
- test/data/css/tests.js
- test/data/html/tests.js
- test/data/javascript/tests.js
Fixes #724
This fix addresses most of the functionality with one major exception. If you set the indent level to zero in CSS and JS, the beautifier still autodetects the indentation of the inputted code. I will be filing a bug for this specific functionality.
> Add indent level options functionality with tests

- js/src/html/beautifier.js
- js/test/generated/beautify-html-tests.js
- test/data/html/tests.js
Fixes #1469 
This change only makes it so new line is preserved for the first hbs attribute.  This doesn't fix or change deeper handlebars/hbs formatting, nor does it cause handlebars to be beautified better insides are still not reindented if they are off.  This only make the beautifier not undo user formatting.
> Preserve new line at start of handlebars contents

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- index.html
- js/src/unpackers/javascriptobfuscator_unpacker.js
- js/src/unpackers/myobfuscate_unpacker.js
- js/src/unpackers/urlencode_unpacker.js
- js/test/sanitytest.js
- package.json
- python/cssbeautifier/__init__.py
- python/cssbeautifier/css/beautifier.py
- python/jsbeautifier/__init__.py
- python/jsbeautifier/unpackers/evalbased.py
- python/jsbeautifier/unpackers/javascriptobfuscator.py
- python/jsbeautifier/unpackers/myobfuscate.py
- python/jsbeautifier/unpackers/packer.py
- python/jsbeautifier/unpackers/urlencode.py
- python/setup.py
- tools/template/beautify-css.wrapper.js
- tools/template/beautify-html.wrapper.js
- tools/template/beautify.wrapper.js
http://jsbeautifier.org now forwards to https://beautifier.io
So does http://jsbeautifier.com.   
This change redirects all emails and other references to beautifier.io.  
Also fix broken bookmarklet.  Added issue to track testing to protect this in future - #1542.
Closes #1399 - https is now on.
> Move to beauitifier.io

- README.md
- js/test/generated/beautify-html-tests.js
- test/data/html/tests.js
Fixes #1518
*Add indent_scripts to README
I went back and plugged it into v1.7.5 and nothing changed.
> Add tests for indent scripts option

- js/src/html/beautifier.js
- js/test/generated/beautify-html-tests.js
- test/data/html/node.mustache
- test/data/html/tests.js
Fixes #1591
NOTE: This is a potentially breaking change to existing behavior.
Whitespace at the start of html used to be ignored.
Now it will be used as the base indent for the rest of the input.
This makes it consistent with the other beautifiers but may change
the behaviors of libraries that use the beautifier.
> Add html/text support to script tag

- js/src/html/beautifier.js
- js/test/generated/beautify-html-tests.js
- test/data/html/tests.js
Fixes https://github.com/beautify-web/js-beautify/issues/1623
The regexp update matches that on line 580 of the same file. As an aside, `#` does not need to be escaped because it is not a special regular expression character.
The js tests have been updated to ensure this works.
I did not see any Python HTML beautifier, so I could not port anything to that language.
Thanks for taking the time to maintain this package!
> Fix indenting of Handlebars/Mustache inverted sections

- js/src/css/beautifier.js
- js/test/generated/beautify-css-tests.js
- python/cssbeautifier/css/beautifier.py
- python/cssbeautifier/tests/generated/tests.py
- test/data/css/tests.js
Fixes Issue: 
CSS allows escape of the `!` character in class names i.e. `.blue\!`, which would be applied to
```<div class="blue!" />```
However, the logic to put a space before `!important` resulted in generating invalid css `.blue\! {` turned into `.blue\ ! {`
N/A --- Added command-line option(s) (NA if -- NA
N/A --- README.md documents new feature/option(s) -- NA
> stop reformatting valid css \! into invalid \ !

- js/src/css/beautifier.js
- js/test/generated/beautify-css-tests.js
- python/cssbeautifier/css/beautifier.py
- python/cssbeautifier/tests/generated/tests.py
- test/data/css/tests.js
Fixes Issue: 
https://github.com/beautify-web/js-beautify/issues/1018
https://github.com/beautify-web/js-beautify/issues/1582
https://github.com/beautify-web/js-beautify/issues/842
> LESS mixin fix

- js/src/html/tokenizer.js
- js/test/generated/beautify-html-tests.js
- test/data/html/tests.js
Style and script elements can have their contents wrapped in cdata or an html comment.
Do not treat other text, such as php tag as though it were one of the wrappers.
Fixes #1687
> Only look for coment and cdata wrappers

- python/jsbeautifier/__init__.py
- raise Exception instead of string to avoid error in python 2.7
- set io encoding to UTF-8, as our code is often UTF-8, instead of same as system default.
- added or corrected command line option names per readme.
> Fix for python 2.7 and cli parameters

- js/src/javascript/acorn.js
- js/src/javascript/tokenizer.js
- js/test/generated/beautify-javascript-tests.js
- python/jsbeautifier/javascript/acorn.py
- python/jsbeautifier/javascript/tokenizer.py
- python/jsbeautifier/tests/generated/tests.py
- test/data/javascript/tests.js
To resolve #1734 , this change modifies the tokenizer to recognize #+identifier as a single word. I first tried just adding # as a valid start character, but that broke existing tests, so this is the way I've been able to fix private fields without regressions.
Fixes Issue: #1734 
Ran `make ci` and all tests are passing including my newly added one.
> Allow # to start identifier, such as private fields in classes

- js/src/html/beautifier.js
- js/test/generated/beautify-html-tests.js
- test/data/html/tests.js
> Add support for es module

- README.md
- js/src/cli.js
- js/src/css/beautifier.js
- js/src/css/options.js
- js/test/generated/beautify-css-tests.js
- python/cssbeautifier/__init__.py
- python/cssbeautifier/css/beautifier.py
- python/cssbeautifier/css/options.py
- python/cssbeautifier/tests/generated/tests.py
- test/data/css/tests.js
Fixes Issue: #1776 ( adding a newline before the opening curly brace of selector(s) )
#1353 
#1259 (partially, till the other options are implemented)
~Name of the new option: `curly-start-newline`~
~Shorthand: `-R` for the `cur` in `curly`~
Added `brace-style=expand` to the css beautifier
> Add expand brace-style option to css beautifier

- index.html
- js/src/html/beautifier.js
- js/src/html/tokenizer.js
- js/test/generated/beautify-html-tests.js
- test/data/html/tests.js
> Fix missing line break at end tag

- Makefile
- azure-pipelines.yml
- package-lock.json
- package.json
`node-static` is out of date and poorly maintained.  Switching to `serve`.
> Switch from node-static to serve

- package.json
Follows https://github.com/beautify-web/js-beautify/pull/1745 which removed Node 8 from the test matrix.
Ref https://github.com/beautify-web/js-beautify/pull/1833.
> Document Node 10 requirement in package.json

- js/src/javascript/beautifier.js
- js/src/javascript/tokenizer.js
- js/test/generated/beautify-javascript-tests.js
- python/jsbeautifier/javascript/tokenizer.py
- python/jsbeautifier/tests/generated/tests.py
- test/data/javascript/tests.js
Updated xml to capture empty tags in both python and JS files
Fixes Issue:  #1854 
> Capture empty tags

- js/src/css/beautifier.js
- js/test/generated/beautify-css-tests.js
- python/cssbeautifier/css/beautifier.py
- python/cssbeautifier/tests/generated/tests.py
- test/data/css/tests.js
Added option max_preserve_newlines to CSS beautifier, as well tests with more lines, less lines and the same as the ones requested in the option.
Fixes #1863: 
> Added option max_preserve_newlines in CSS beautifier

- js/src/javascript/beautifier.js
- js/test/generated/beautify-javascript-tests.js
- python/jsbeautifier/javascript/beautifier.py
- python/jsbeautifier/tests/generated/tests.py
- test/data/javascript/tests.js
Fixes Issue: 
- [NA] Added command-line option(s) (NA if
- [NA] README.md documents new feature/option(s)
> Issue #1858- Space-before-conditional: false doesn't work on switch case statement

- python/cssbeautifier/_main.py
- python/cssbeautifier/css/options.py
- python/jsbeautifier/__init__.py
- python/jsbeautifier/cli/__init__.py
- python/jsbeautifier/tests/shell-test.sh
Please do notice that the default value of `keep_quiet` is different from js-beautify as there's no option to control it and I decided not to make it - python's part of the project doesn't seem very active anyway.
Fixes Issues: 
`-n` matching incorrect option. `("--preserve**-n**ewlines")` is not a tuple but a string.
```python3
>>> '-n' in ("--preserve-newlines")
True
>>> '-n' in ("--preserve-newlines",)
False
```
missing config option appearing if there are no changes:
```
'BeautifierOptions' object has no attribute 'keep_quiet'
```
keep_quiet didn't actually quiet `beautified FILE` message
> python: fix argument parsing, missing css-beautify config option

- js/src/cli.js
- package-lock.json
- package.json
In Node.js 10 and later, recursive mkdir is available in core. No longer needs the `mkdirp` package.
<https://nodejs.org/docs/latest-v10.x/api/fs.html#fs_fs_mkdirsync_path_options>
Ref https://github.com/11ty/eleventy/issues/1375.
> Use native mkdirSync instead of 'mkdirp' package

- js/src/javascript/tokenizer.js
- python/jsbeautifier/javascript/tokenizer.py
- test/data/javascript/tests.js
Fixes Issue: 
#1934 js-beautify inserts space in hexadecimal bigint literals.
- NA Added command-line option(s) (NA if
- NA README.md documents new feature/option(s)
> Allow bigint octals, binarys and hexadecimals - beautify-web#1934 

- js/src/javascript/beautifier.js
- python/jsbeautifier/javascript/beautifier.py
- test/data/javascript/tests.js
Wrong indentation observed when the last line in a case is a right brace.
```
switch (x) {
case 0:
if (y == z) {
a();
} else {
b();
}
case 1:
c();
}
```
(same as input)
```
switch (x) {
case 0:
if (y == z) {
a();
} else {
b();
}
case 1:
c();
}
```
```
switch (x) {
case 0:
if (y == z) {
a();
} else {
b();
}
case 1:
c();
}
```
Deindent for case/default token is skipped whenever the previous
token is a right brace.
However this logic doesn't always work as highlighted in the issue.
Added code to skip deindent only if the closing right brace corresponds to
opening left brace of case action block.
Fixes Issue: https://github.com/beautify-web/js-beautify/issues/1683
- [NA] Added …
> issue #1683: fix switch case indentation

- js/src/html/beautifier.js
- test/data/html/tests.js
Fix handling of handlebars partial blocks with whitespace or parameters following partial name.
Fixes Issue: #1946
> Support handlebars partial blocks with parameters

- Makefile
The latest release of black has introduced breaking changes which affect the ci pipeline and python test. Specify a version for download until that can be fixed.
Fixes Issue: 
#1995
> bug: fix psf/black package version

- web/onload.js
> feature: allow mac users to use command+enter for submit button

- js/src/javascript/beautifier.js
- python/jsbeautifier/javascript/beautifier.py
- test/data/javascript/tests.js
Checking to make sure that the token with text 'class' or 'interface' has whitespace after it to be considered a block statement, otherwise treat as object literal
Fixes Issue: 
#1838
> 'class' as a object property name

- js/src/css/beautifier.js
- python/cssbeautifier/css/beautifier.py
- test/data/css/tests.js
Fix issues with spacing in LESS code when using object literals inside mixins. The changes in this PR could be considered breaking since but I believe they are correct.
Fixes Issue: 
- https://github.com/beautify-web/js-beautify/issues/722
- https://github.com/beautify-web/js-beautify/issues/2016
- https://github.com/microsoft/vscode/issues/146693
Fixes #722
Fixes #2016
> [LESS] Fixing issues with spacing when an object literal lives inside a mixin

- js/src/css/beautifier.js
- python/cssbeautifier/css/beautifier.py
- test/data/css/tests.js
This PR has two separate fixes.
Case 1: String followed by anything loses spacing in middle
```
div {
grid-template: "top" 1px;
}
```
Case 2: Preserve multiline for `grid-template` property
```
.grid {
grid-template:
"top-bar top-bar" 100px
"left-bar center" 100px 
}
```
Fixes #1817
> Fix issue #1817 - grid-template property css

- index.html
Add a link to the python library on the main site
Fixes Issue: 
- #2030
> Fixes #2030 - Add a link to the python library on the main site

- js/src/css/beautifier.js
- python/cssbeautifier/css/beautifier.py
- test/data/css/tests.js
Add grid-template-areas to NON_SEMICOLON_NEWLINE_PROPERTY list. The significance of this change is visible when we start comparing entire string tokens. Right now we compare character by character and in that case `grid-template` and `grid-template-areas` will both pass the check but when we start comparing entire tokens the property name needs to be correct.
> Add grid-template-areas to NON_SEMICOLON_NEWLINE_PROPERTY list

- js/src/html/beautifier.js
- test/data/html/tests.js
Fixes Issue: 
#1988 "Fails to recognize Handlebars block with whitespace control, e.g. {{~#if true ~}}"
Added the whitespace control character inside the `tag_check_match` for the html beautifier. The control character also affected the token for partial handlebars `{{#>` to `{{~#>` which I also added a check for. Additionally, if the character is included at the start of handlebars, the test for non single handlebars tags will start at character 3 instead of character 2.
I added unit tests checking that issue 1988 was fixed, and that previous handlebar formatting fixes would not break with the inclusion of "~" at the start.
- [NA] Python implementation (NA if HTML beautifier)
- …
> [Issue #1988] Added support to recognize Handlebars block with whitespace control

- js/src/html/beautifier.js
- test/data/html/tests.js
Fixes Issue: #1869 "html formatter doesn't support handlebars partial blocks"
Created a new conditional that checks for '{{#>' and '{{~#>' at the beginning of an html block. If it finds either of these, separates the partial from the tag and properly assigns the tag.  
I added unit tests checking that issue 1869 was fixed for partials not separated by spaces as well as unit tests checking that partials separated by spaces still had correct behavior 
- [ X] Python implementation (NA if HTML beautifier)
- [ X] Added command-line option(s) (NA if
> solution to partials not seperated by spaces

- python/jsbeautifier/javascript/beautifier.py
The Python version changed the wrong variable, which means that the
test fails.
This patch changes the variable from '_flags.whitespace_before' to
'_output.space_before_token'.
This test was executed from package downloaded from PyPI.
```
======================================================================
FAIL: test_beautifier (jsbeautifier.tests.generated.tests.TestJSBeautifier)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/<<PKGBUILDDIR>>/jsbeautifier/tests/generated/tests.py", line 8028, in test_beautifier
bt('1000000000000001000 .toFixed(0)!==1000000000000001024', '1000000000000001000 .toFixed(0) !== 1000000000000001024')
File "/<<PKGBUILDDIR>>/jsbeautifier/tests/generated/tests.py", line 10337, in bt …
```
> Fix test 'Do not remove whitespace after number'

- js/src/html/beautifier.js
- test/data/html/tests.js
Custom elements are any elements whose tags contain a dash: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#high-level_view
Fixes Issue: https://github.com/beautify-web/js-beautify/issues/1989
> Avoid layout-breaking whitespace by treating all custom elements as inline elements.

- README.md
I added some more explanations and examples on how to use `js_beautify` when using directly with a script tag.
Fixes Issue: 
None. Improves documentation.
> Doc: Updates web browser implementation examples

- js/src/html/beautifier.js
- test/data/html/tests.js
A minor patch for:
- correctly formatting nested `<menu>` tags, such as `<li>` tags inside `<menu>` tags inside `<li>` tags;
- allowing unclosed `<p>` tags followed by a `<menu>` tag.
Basically, `<menu>` elements should be treated as identical to `<ul>` elements.
References:
> *The `menu` element is simply a semantic alternative to [`ul`](https://html.spec.whatwg.org/multipage/grouping-content.html#the-ul-element) to express an unordered list of commands (a "toolbar").*
> (https://html.spec.whatwg.org/multipage/grouping-content.html#the-menu-element)
> A `p` element's end tag can be omitted if the `p` element is immediately followed by an `address`, `article`, ..., `main`, **`menu`**, `nav`, `ol`, ..., `table`, or `ul` element, or...
> …
> Fix formatting related to the <menu> element

- js/src/javascript/beautifier.js
- python/jsbeautifier/javascript/beautifier.py
- test/data/javascript/node.mustache
- test/data/javascript/tests.js
This change makes sure that a new line is added everytime a semicolon is followed by a block statement
Fixes Issue: 
fixes #1852
> fix - semicolon followed by block statement doesnt have new line

- python/jsbeautifier/javascript/beautifier.py
- tools/template/beautify.wrapper.js
There are small typos in:
- python/jsbeautifier/javascript/beautifier.py
- tools/template/beautify.wrapper.js
Fixes:
- Should read `conditional` rather than `conditionial`.
- Should read `overridden` rather than `overriden`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- python/cssbeautifier/__init__.py
- [ x ] Source branch in your fork has meaningful name (not `main`)
Fixes Issue: 
`beautify_file` of `cssbeautifier` (python module) not working because usage of two different variable names `file` and `file_name`. 
See `__init__.py`:
```python
...
def beautify_file(file_name, opts=None):
_main = __import__("cssbeautifier", globals(), locals(), ["_main"])._main
return _main.beautify_file(file, opts)
...
```
results in:
```python
import cssbeautifier
cssbeautifier.beautify_file('./file.css')
```
```shell
$ python file.py         
Traceback (most recent call last):
File ".../file.py", line 3, in <module>
x = cssbeautifier.beautify_file('./file.css')
File ".../cssbeautifier/__init__.py", line 41, in beautify_file
return _main.beautify_file(file, opts)
NameError: name 'file' is not defined. …
```
> use correct variable name

- .github/workflows/main.yml
- python/cssbeautifier/_main.py
- python/cssbeautifier/css/beautifier.py
- python/jsbeautifier/__init__.py
- python/jsbeautifier/core/directives.py
- python/jsbeautifier/core/output.py
- python/jsbeautifier/core/templatablepattern.py
- python/jsbeautifier/javascript/beautifier.py
- python/jsbeautifier/javascript/tokenizer.py
> Fix CI build

- js/src/css/beautifier.js
- test/data/css/tests.js
Fixes Issue: #2012 
Previous Closed Pull Request : #2142 
Corrects this Tailwindcss specific error : 
Before : 
```
h3 {
@apply flex flex-col lg:flex-row space-y-3 lg:space-x-12 items-start;
}
```
After : 
```
h3 {
@apply flex flex-col lg: flex-row space-y-3 lg:space-x-12 items-start;
}
```
This PR fixes the extra space added after the first `:` following the `@apply` custom at rule when CSS beautifying. 
> CSS insideNonNestedAtRule generic variable 

- test/data/javascript/python.mustache
Fixes Issue: 
Commit c90470061c775a42b9c7a99840d2a5d436a89407 forgot to update the tests for Python, this commit updates the test-case to be equivalent to that of 'node.mustache' and to support the fix for #1852, which was implemented in #2117.
> Fix 'brace-style' tests for Python

- package-lock.json
- package.json
See #2168.  Transitive dependency `commander v10.x` requires nodejs v14.x.
Note, we only test on v16.x and above so this is not a guaranteed minimum. 
Fixes Issue: 
> Set nodejs minimum to v14

- index.html
- web/common-function.js
This marks the "Detect packers and obfuscators" feature as unsafe and disables it by default on the web interface.
Fixes Issue: #662 
> Mark unpacking feature as unsafe

- js/src/javascript/acorn.js
- js/src/javascript/tokenizer.js
- python/jsbeautifier/javascript/acorn.py
- python/jsbeautifier/javascript/tokenizer.py
- test/data/javascript/node.mustache
- test/data/javascript/python.mustache
- test/data/javascript/tests.js
Fixes Issue: Invalid prettification of object with unicode escape character as object key [#2159](https://github.com/beautify-web/js-beautify/issues/2159)
> Handle ES6 unicode code point syntax

- python/jsbeautifier/unpackers/packer.py
`'\('` raises a `DeprecationWarning`, because `\(` is not a valid escape sequence in Python:
```
tests/unit/test_cli/test_schema_commands.py::test_openapi_typescript_command[Custom-]
D:\a\litestar\litestar\.venv\Lib\site-packages\jsbeautifier\unpackers\packer.py:31: DeprecationWarning: invalid escape sequence '\('
"eval[ ]*\([ ]*function[ ]*\([ ]*p[ ]*,[ ]*a[ ]*,[ ]*c["
```
Link: https://github.com/litestar-org/litestar/actions/runs/6282794210/job/17062629903#step:11:71
But, `r'\('` is actually fine. So, let use it!
> Use raw strings to define a regex in `packer.py`

- index.html
- package-lock.json
- package.json
Manually verified page functionality.
> Update codemirror and other web page dependencies

- js/src/cli.js
- js/src/core/options.js
- js/src/html/options.js
- python/jsbeautifier/core/options.py
- python/jsbeautifier/tests/core/test_options.py
- test/data/html/tests.js
The new angular templating caused unintended side-effects when turned on by default.  This changes it by off by default.
Fixes #2246 
> Turn new angular templating off by default in html

- test/data/javascript/python.mustache
In Python 3.12 `SyntaxWarning` is generated because of invalid escape sequences.
Changed `\s` -> `\\s`.
```
/<<PKGBUILDDIR>>/jsbeautifier/tests/generated/tests.py:87: SyntaxWarning: invalid escape sequence '\s'
bt('a = /\s+/')
/<<PKGBUILDDIR>>/jsbeautifier/tests/generated/tests.py:89: SyntaxWarning: invalid escape sequence '\s'
bt('"\\u2022";a = /\s+/;"\\x41\\x42\\x43\\x01".match(/\\x41/);','"\\u2022";\na = /\s+/;\n"\\x41\\x42\\x43\\x01".match(/\\x41/);')
/<<PKGBUILDDIR>>/jsbeautifier/tests/generated/tests.py:89: SyntaxWarning: invalid escape sequence '\s'
bt('"\\u2022";a = /\s+/;"\\x41\\x42\\x43\\x01".match(/\\x41/);','"\\u2022";\na = /\s+/;\n"\\x41\\x42\\x43\\x01".match(/\\x41/);')
/<<PKGBUILDDIR>>/jsbeautifier/tests/generated/tests.py:113: SyntaxWarning: invalid escape sequence '\s' …
```
> Properly escape '\s' in test file

- js/src/core/templatablepattern.js
- js/src/html/beautifier.js
- js/src/html/tokenizer.js
- test/data/html/tests.js
Fixes Issue: https://github.com/beautifier/js-beautify/issues/2260
> Fixed #2260 - <style> and <script> tags indentation if also indenting angular control flows

- python/setup-css.py
- python/setup-js.py
`make pytest` already runs a superset of all the tests run by `python3 setup-css.py test` and `python3 setup-js.py test`.  (The former didn't work anyway due to a typo.)
Fixes Issue: #2300, #2301
> Remove obsolete setuptools test integration

- python/jsbeautifier/core/templatablepattern.py
- [ -] Source branch in your fork has meaningful name (not `main`)
Fixes Issue: 
The templatablepattern.py contained the bug:
```python
def read(self):
if self._until_after:
result += self._input.readUntilAfter(self._until_after) # should be self._until_pattern
```
the self._until_after is bool flag, while the `readUntilAfter` accepts the regexp.
The same code in templatablepattern.js uses the this._until_pattern correctly.
- [- ] Python implementation (NA if HTML beautifier)
> one-line bug in templatablepattern.py

- index.html
- js/bin/js-beautify.js
- web/common-function.js
- web/onload.js
This pull request introduces a new feature to the js-beautify project: a "Download Code" button that allows users to download the beautified code in the format they choose (HTML, CSS, or JS). 
Fixes Issue: 
- #2309 
1. **Added Download Button to `index.html`**
- A new button labeled "Download Beautified Code" has been added to the HTML.
- Clicking this button triggers the `downloadBeautifiedCode` function.
2. **Implemented `downloadBeautifiedCode` Function**
- Added a function in `web/common-function.js` to handle the download functionality.
- The function generates a Blob from the beautified code and initiates a download with a filename based on the selected language.
- **New Button Added:**
```html
<button class="control" type="button" onclick="downloadBeautifiedCode()"><strong>Download …
```
> Added a download button

- .github/workflows/milestone-publish.yml
- tools/release-all.sh
> build wheel for pypi package

- package-lock.json
- package.json
Fixes Issue: 
#2349 `glob` dropped node < 20 support in version 11. `js-beautify` promises wider Node version range so here it is downgraded to the last one that supports node 18.
> fix node 18 support by downgrading glob to v10
