beautifier/js-beautify

js/lib/beautify-html.js
This is a huge pull request which is of top priority. Drop everything and get this merged!
:smile:
=> fix "iff" typo

js/lib/beautify-css.js, js/lib/beautify-html.js, js/test/beautify-html-tests.js, python/cssbeautifier/__init__.py, test/data/html.js
Simple fix to interpret ident-with-tabs option in javascript implementation
=> Fixes issue #587 for javascript implementation

CONTRIBUTING.md, index.html
Fixes a few typos and capitalization.
=> Simple, minor grammar fixes

js/lib/beautify-html.js, js/test/beautify-css-tests.js, test/template/node-css.mustache
See discussion here: https://github.com/beautify-web/js-beautify/commit/1b4be9b13cf53dfcbc4bf917a97d4bb0d96fccf0#commitcomment-11757796
First of all is needed for my port for <a href="http://akelpad.sourceforge.net/">AkelPad</a> editor:
https://github.com/Infocatcher/AkelPad_scripts/blob/master/jsBeautifier.js
http://akelpad.sourceforge.net/forum/viewtopic.php?p=11246#11246
And finally yay!
=> Support for legacy JavaScript versions (e.g. WSH+JScript & Co)

js/lib/beautify.js, js/test/beautify-javascript-tests.js, python/jsbeautifier/__init__.py, python/jsbeautifier/tests/testjsbeautifier.py, test/data/javascript.js
=> Fixed issue with ES6 support for octal strings as 0o123.

js/lib/beautify-html.js
=> Add missing 'var' declaration.

js/lib/beautify-html.js, js/test/beautify-html-tests.js, test/template/node-html.mustache
Add support for script type "application/json" and "application/ld+json".
=> Resolve #821

js/lib/beautify.js, js/lib/cli.js, js/test/shell-smoke-test.sh, python/jsbeautifier/__init__.py, python/jsbeautifier/tests/shell-smoke-test.sh
=> Add eol = "auto" option as the default behavior.

.gitignore, js/lib/beautify-html.js, js/test/generated/beautify-html-tests.js, js/test/shell-smoke-test.sh, python/jsbeautifier/tests/shell-smoke-test.sh, test/data/html/tests.js
=> Treat php tags as single in html

js/lib/beautify-html.js, js/test/generated/beautify-html-tests.js, test/data/html/tests.js
Fixes https://github.com/beautify-web/js-beautify/issues/640
=> Obey `wrap_attributes_indent_size` after auto wrap

README.md, tools/release-all.sh
=> Add CDN url to readme

js/lib/beautify.js, js/test/generated/beautify-javascript-tests.js, python/jsbeautifier/__init__.py, python/jsbeautifier/tests/generated/tests.py, test/data/javascript/tests.js
=> Fixed JSX Multiline root tag

js/lib/cli.js, js/test/shell-smoke-test.sh, python/jsbeautifier/__init__.py, python/jsbeautifier/tests/shell-smoke-test.sh
=> Added support for editorconfig from stdin

js/lib/beautify-html.js, js/test/generated/beautify-html-tests.js, test/data/html/tests.js
=> Ignore linebreak when meet handlebar

js/lib/beautify-html.js, js/test/generated/beautify-html-tests.js, test/data/html/tests.js
Fixes attribute wrapping issues.
=> Fix #1102 and fix #1103

js/lib/beautify.js, js/src/javascript/beautifier.js, js/test/generated/beautify-javascript-tests.js, package-lock.json, python/jsbeautifier/javascript/beautifier.py, python/jsbeautifier/tests/generated/tests.py, test/data/javascript/tests.js, tools/template/beautify.begin.js
=> Remove Object.value polyfill

CONTRIBUTING.md, README.md, js/lib/beautify-html.js, js/lib/cli.js, tools/template/beautify-html.begin.js
I mean, "whose" *sounds* like it's the intended verbiage, but I dunno, not a linguist.
=> Change "that its" to "whose"

CONTRIBUTING.md
As I was preparing to contribute (expect another PR hopefully soon), I noticed a couple of typos in the Contributing doc.
=> Fix many "implemnations"

tools/build.sh
Fixes issue [1312](https://github.com/beautify-web/js-beautify/issues/1312)
=> Use same version of `pip` as `python`

js/lib/beautify-html.js, js/src/html/beautifier.js, js/test/generated/beautify-html-tests.js, test/data/html/tests.js
=> Prevent exception during anchor tag

js/lib/beautify-html.js, js/src/html/beautifier.js, js/test/generated/beautify-html-tests.js, test/data/html/tests.js
=> Prevent indent after PHP echo tag (<?= ... ?>)

js/lib/beautify-html.js, js/src/html/beautifier.js, js/test/generated/beautify-html-tests.js, test/data/html/tests.js
=> Fix multiline tags with line break before whitespace

python/jsbeautifier/tests/test-packer.py, python/jsbeautifier/unpackers/packer.py
=> handle case when radix = []

CONTRIBUTING.md, index.html, web/common-function.js, web/onload.js
=> Serve instructions

index.html, web/common-function.js
=> Add issue open button with templating

js/lib/beautify.js, js/src/javascript/beautifier.js, js/test/generated/beautify-javascript-tests.js, package-lock.json, python/jsbeautifier/javascript/beautifier.py, python/jsbeautifier/tests/generated/tests.py, test/data/javascript/tests.js
=> Fixed incorrect unindent for if else blocks

index.html, package-lock.json
Added [missing] doctype and possibly followed HTML5 spec in that I believe the first thing immediately after the head tag is supposed to be the charset; also added the old charset method for possible increased compatibility.
=> Updated index.html

js/lib/beautify-css.js, js/src/css/beautifier.js, js/test/generated/beautify-css-tests.js, python/cssbeautifier/css/beautifier.py, python/cssbeautifier/tests/generated/tests.py, test/data/css/tests.js
=> Fixes :hover for @extend issue

js/lib/beautify.js, js/src/javascript/beautifier.js, js/test/generated/beautify-javascript-tests.js, python/jsbeautifier/javascript/beautifier.py, python/jsbeautifier/tests/generated/tests.py, test/data/javascript/tests.js
=> Await import() support

js/test/generated/beautify-html-tests.js, js/test/generated/beautify-javascript-tests.js, python/jsbeautifier/tests/generated/tests.py, test/data/html/tests.js, test/data/javascript/tests.js
=> Another line wrap test

js/lib/beautify-html.js, js/src/html/beautifier.js, js/test/generated/beautify-html-tests.js, test/data/html/tests.js
=> Keeps inline comments with closing tag

js/src/core/inputscanner.js, js/src/javascript/tokenizer.js, js/test/generated/beautify-javascript-tests.js, python/jsbeautifier/javascript/tokenizer.py, python/jsbeautifier/tests/generated/tests.py, test/data/javascript/tests.js
Fixes #1334
Some issue compiling after updating the Python tokenizer
=> Xml detection fix

.gitignore, .travis.yml, CONTRIBUTING.md, Makefile, appveyor.yml, build, tools/build.sh, tools/git-status-clear.sh, tools/node, tools/npm, tools/python
This has a number of advantages in faster build times and simpler commands.
=> Switch to make

js/src/css/beautifier.js, js/src/javascript/tokenizer.js, js/test/generated/beautify-css-tests.js, python/cssbeautifier/css/beautifier.py, python/cssbeautifier/tests/generated/tests.py, test/data/css/tests.js
=> Fix LESS variable formatting

js/src/javascript/beautifier.js, js/test/generated/beautify-javascript-tests.js, python/jsbeautifier/javascript/beautifier.py, python/jsbeautifier/tests/generated/tests.py, test/data/javascript/tests.js
=> Ensure space between adjacent words in js

js/test/generated/beautify-html-tests.js, test/data/html/tests.js
Fixes #576
Fixes #1237 
Just a test for an issue that was already fixed in previous version.
=> Add test for Handlebars indenting issue

js/test/generated/beautify-html-tests.js, test/data/html/tests.js
Fixes #1222
Add test for issue that was fixed in prior version
=> Add test for p tag formatting issue resolved in prior version

js/src/html/beautifier.js, js/test/generated/beautify-html-tests.js, test/data/html/tests.js
=> Self closing tags space handling

js/test/generated/beautify-css-tests.js, python/cssbeautifier/tests/generated/tests.py, test/data/css/tests.js
Fixes #1373 
Added test for issue resolved in v1.8.0-rc4
=> Test for spacing around attribute value selector

js/src/css/beautifier.js, js/test/generated/beautify-css-tests.js, python/cssbeautifier/css/beautifier.py, python/cssbeautifier/tests/generated/tests.py, test/data/css/tests.js
=> Preserve newline in block css property values

js/src/css/beautifier.js, js/test/generated/beautify-css-tests.js, python/cssbeautifier/css/beautifier.py, python/cssbeautifier/tests/generated/tests.py, test/data/css/tests.js
=> Support @import in CSS

js/test/generated/beautify-html-tests.js, test/data/html/node.mustache, test/data/html/tests.js
Closes #348
Added test to already resolved issue as of v1.8.0-rc6
=> Adds test to preserve newlines

js/src/core/output.js, js/src/css/beautifier.js, js/test/generated/beautify-css-tests.js, python/cssbeautifier/css/beautifier.py, python/cssbeautifier/tests/generated/tests.py, python/jsbeautifier/core/output.py, test/data/css/tests.js
=> Force newlines between nested rules in SCSS

js/src/core/options.js, js/src/css/beautifier.js, js/src/html/beautifier.js, js/src/javascript/beautifier.js, js/test/generated/beautify-css-tests.js, js/test/generated/beautify-html-tests.js, js/test/generated/beautify-javascript-tests.js, python/cssbeautifier/css/beautifier.py, python/cssbeautifier/tests/generated/tests.py, python/jsbeautifier/core/options.py, python/jsbeautifier/javascript/beautifier.py, python/jsbeautifier/tests/generated/tests.py, test/data/css/node.mustache, test/data/css/python.mustache, test/data/html/node.mustache, test/data/javascript/node.mustache, test/data/javascript/python.mustache
=> Converts name dashes to underscore in option inputs

js/test/generated/beautify-html-tests.js, test/data/html/tests.js
=> Add test for ASPX JSP directives formatting

js/test/generated/beautify-html-tests.js, test/data/html/tests.js
=> Add test for formatting handlebars with nbsp

js/test/generated/beautify-html-tests.js, test/data/html/tests.js
=> Add test for wrap attributes force aligned

js/test/generated/beautify-html-tests.js, test/data/html/tests.js
=> Add test for expressions inside handlebars

js/test/generated/beautify-css-tests.js, python/cssbeautifier/tests/generated/tests.py, test/data/css/tests.js
=> Add test for newlines in css @media blocks

js/test/generated/beautify-html-tests.js, test/data/html/tests.js
=> Add test for SVG formatting

js/test/generated/beautify-html-tests.js, test/data/html/tests.js
=> Add test for handlebars with wrap attributes

js/src/html/beautifier.js, js/test/generated/beautify-html-tests.js, test/data/html/tests.js
=> Update unindent method for each else blocks

js/src/javascript/beautifier.js, js/test/generated/beautify-javascript-tests.js, python/jsbeautifier/javascript/beautifier.py, python/jsbeautifier/tests/generated/tests.py, test/data/javascript/tests.js
Fixes #1282
Refactor TOKEN.RESERVED to reserved_word and reserved_array functions
=> Improved default handling in case blocks

js/src/css/beautifier.js, js/test/generated/beautify-css-tests.js, python/cssbeautifier/tests/generated/tests.py, test/data/css/tests.js
Fixes #1535
@MacKLess  Could you take a look at this?
=> Fixed support for data URI with test

web/common-function.js
Fixes #789
I will be filing an issue (task) for tests on this type of functionality
=> Fixes indentation in second comment on webpage

js/src/javascript/beautifier.js, js/test/generated/beautify-javascript-tests.js, python/jsbeautifier/javascript/beautifier.py, python/jsbeautifier/tests/generated/tests.py, test/data/javascript/tests.js
=> Fix formatting for Typescript declare

README.md, js/src/cli.js, js/src/javascript/beautifier.js, js/src/javascript/options.js, js/test/generated/beautify-javascript-tests.js, python/jsbeautifier/__init__.py, python/jsbeautifier/javascript/beautifier.py, python/jsbeautifier/javascript/options.py, python/jsbeautifier/tests/generated/tests.py, test/data/javascript/tests.js
=> Add option for space before named function

js/src/javascript/beautifier.js, js/test/generated/beautify-javascript-tests.js, python/jsbeautifier/javascript/beautifier.py, python/jsbeautifier/tests/generated/tests.py, test/data/javascript/tests.js
=> Fix dynamic import arrow support

js/src/javascript/tokenizer.js, js/test/generated/beautify-javascript-tests.js, python/jsbeautifier/javascript/tokenizer.py, python/jsbeautifier/tests/generated/tests.py, test/data/javascript/tests.js
=> Fix extendscript #include

README.md, js/src/cli.js, js/src/html/beautifier.js, js/src/html/options.js, js/test/generated/beautify-html-tests.js, test/data/html/tests.js
=> Add preserve and preserve_align to html

js/src/javascript/beautifier.js, js/test/generated/beautify-javascript-tests.js, python/jsbeautifier/javascript/beautifier.py, python/jsbeautifier/tests/generated/tests.py, test/data/javascript/tests.js
=> Fix object literal async indenting

README.md
Also show that it's a valid option in the  config file.
=> Document the default value of "editorconfig"

js/config/defaults.json, js/src/javascript/beautifier.js, js/test/generated/beautify-javascript-tests.js, python/jsbeautifier/javascript/beautifier.py, python/jsbeautifier/tests/generated/tests.py, test/data/javascript/tests.js
=> in the .vue file `space_after_anon_function` is invalid #1425

js/src/javascript/beautifier.js
=> Move MODE use to after definition

js/src/cli.js, js/test/shell-test.sh, python/jsbeautifier/tests/shell-test.sh
Fixed #1609 (see the details in this issue)
=> Fix #1609 stdin marker "-" is ignored error

Makefile, README.md, index.html, js/src/cli.js, js/src/core/options.js, js/src/core/output.js, js/test/generated/beautify-css-tests.js, js/test/generated/beautify-html-tests.js, js/test/generated/beautify-javascript-tests.js, python/cssbeautifier/__init__.py, python/cssbeautifier/tests/generated/tests.py, python/jsbeautifier/__init__.py, python/jsbeautifier/core/options.py, python/jsbeautifier/core/output.py, python/jsbeautifier/tests/generated/tests.py, python/test-perf-jsbeautifier.py, test/data/css/tests.js, test/data/html/tests.js, test/data/javascript/tests.js, web/common-function.js
This option allows to keep indentation on empty lines.
=> New option: indent_empty_lines

js/test/generated/beautify-javascript-tests.js, python/jsbeautifier/javascript/tokenizer.py, python/jsbeautifier/tests/generated/tests.py, test/data/javascript/tests.js
Fixing https://github.com/beautify-web/js-beautify/issues/1658
First we need to verify whether there is another input before matching its value.
=> Fixing https://github.com/beautify-web/js-beautify/issues/1658

CONTRIBUTING.md
=> Removed duplicate "and"

js/src/html/beautifier.js, js/src/html/tokenizer.js, js/src/javascript/tokenizer.js, js/test/generated/beautify-html-tests.js, js/test/generated/beautify-javascript-tests.js, python/jsbeautifier/javascript/tokenizer.py, python/jsbeautifier/tests/generated/tests.py, test/data/html/tests.js, test/data/javascript/node.mustache, test/data/javascript/python.mustache
=> Comment wrapping

js/test/generated/beautify-javascript-tests.js, python/jsbeautifier/tests/generated/tests.py, test/data/javascript/tests.js
=> Tests: Fix typo

index.html
Adds the required addons for the codemirror search on the website.
Fixes Issue: 
closes #1696
=> Add codemirror search plugin

README.md
https://stackoverflow.com/questions/41060343/beautify-html-with-js-beautify-from-command-line#comment75350731_41060343
=> Note that Python version only works with JS files

package-lock.json, package.json
=> Update to latest mocha

js/src/html/beautifier.js, js/test/generated/beautify-html-tests.js, test/data/html/tests.js
=> Added optional closing of p tags

js/src/javascript/tokenizer.js, js/test/generated/beautify-javascript-tests.js, python/jsbeautifier/javascript/tokenizer.py, python/jsbeautifier/tests/generated/tests.py, test/data/javascript/tests.js
=> Support optional chaining

js/src/html/beautifier.js, js/test/generated/beautify-html-tests.js, test/data/html/tests.js
=> Add support for handlebars partials

js/src/unpackers/p_a_c_k_e_r_unpacker.js, python/jsbeautifier/unpackers/packer.py, python/jsbeautifier/unpackers/tests/testpacker.py
=> python jsbeautifier - handle non-ascii chars

index.html, web/common-function.js, web/common-style.css
- [✅ ] Source branch in your fork has meaningful name (not `master`)
Added copy to clipboard and select buttons to the web interface.
Fixes Issue: 
Fixes #1805
- [ NA ] JavaScript implementation
- [ NA ] Python implementation (NA if HTML beautifier)
- [ NA ] Added Tests to data file(s)
- [ NA ] Added command-line option(s) (NA if
- [ NA ] README.md documents new feature/option(s)
=> Add copy to clipboard and select all buttons

Makefile, python/cssbeautifier/_main.py, python/jsbeautifier/__init__.py, python/jsbeautifier/cli/__init__.py, python/jsbeautifier/core/options.py, python/jsbeautifier/javascript/options.py, python/jsbeautifier/tests/shell-test.sh, python/setup-js.py
This change also adds smoke tests for installed cssbeautifier
package.
=> Refactor python cssbeautifier to reuse jsbeautifier CLI methods

README.md, js/src/cli.js, js/src/core/options.js, js/src/core/templatablepattern.js, js/src/html/options.js, js/test/generated/beautify-html-tests.js, python/jsbeautifier/__init__.py, python/jsbeautifier/core/options.py, python/jsbeautifier/core/templatablepattern.py, test/data/html/tests.js
Fixes Issue: 
Added basic [smarty ](https://www.smarty.net/) templating support. Resolves #1820
=> Basic Smarty templating

index.html
=> add  viewport meta tag to index.html

js/src/javascript/beautifier.js, js/test/generated/beautify-javascript-tests.js, python/jsbeautifier/javascript/beautifier.py, python/jsbeautifier/tests/generated/tests.py, test/data/javascript/tests.js
Added validations to prevent tagged literals from being modified
Fixes Issue:  #1244 
=> Fixing bug #1244

js/src/javascript/beautifier.js, js/test/generated/beautify-javascript-tests.js, python/jsbeautifier/javascript/beautifier.py, python/jsbeautifier/tests/generated/tests.py, test/data/javascript/tests.js
=> Fix for obj?.[expr] optional chaining syntax

package-lock.json
=> Security fixes

package.json
=> Use IE 11 browserlist for webpack

index.html, web/common-function.js
Added and clear button to the website
#1924
=> Added buttons to website

js/src/javascript/beautifier.js, python/jsbeautifier/javascript/beautifier.py, test/data/javascript/tests.js
=> handle bitwise ~ operator

.github/workflows/main.yml
=> Update Node versions in CI, remove Node 10

Makefile, python/jsbeautifier/javascript/beautifier.py, python/jsbeautifier/unpackers/packer.py, python/pyproject.toml
=> Remove lock on python black version

js/src/css/beautifier.js, python/cssbeautifier/css/beautifier.py, test/data/css/tests.js
Adds basic support for SCSS/SASS maps. Still missing lots of other edge cases but this is a good start
Partially Fixes Issue: 
- #1236
=> Adding basic support for SCSS/SASS maps

test/data/javascript/tests.js
Adding some regression tests to confirm #1151
Fixes Issue: 
- #1151
=> Adding some regression tests to confirm #1151

test/data/css/tests.js
Issue was fixed in #2018, just adding regression tests here #1798
Fixes Issue: 
- #1798
=> Adding regression tests for #1798

test/data/javascript/tests.js
Added regression test to confirm issue is fixed
Fixes Issue: 
- Fixes #772
=> Fixes #772 - Added regression tests 

index.html, web/common-style.css
Redesigned the front facing beautifier.io website to be much cleaner looking with responsive design that can now work on mobile devices. This is an opinionated redesigned version of the site. It is a quick overhaul which can be improved over time. It is also responsive enough that we can use the site from mobile. I have added some pics below to show the differences.
**Old Site Desktop:**
**New Site Desktop:**
**Old Mobile Site:**
**New Mobile Site:**
Fixes Issue: 
- Fixes #1444
=> Fixes #1444 - Redesigned website

CHANGELOG.md, tools/generate-changelog.sh, tools/release-all.sh
Fixes the broken changelog update process by updating the generate-changelog.sh script to use the new github api with authorization tokens.
Fixes Issue: 
- Fixes #2022
=> Fixes #2022 - Broken Changelog proces

js/src/css/beautifier.js, python/cssbeautifier/css/beautifier.py, test/data/css/tests.js
Adding support for the new `@forwards` syntax in SASS
Fixes Issue: 
- Fixes #1976
=> Fixes #1976 Adding support for the new @forwards syntax in SASS

README.md, tools/release-all.sh
=> Remove rawgit

js/src/css/beautifier.js, python/cssbeautifier/css/beautifier.py, test/data/css/tests.js
=> Fix two spacing issue in CSS

index.html, package-lock.json, package.json, web/common-function.js, web/common-style.css
=> Dependency updates and UI tweaks

Makefile, js/src/cli.js
Fixes Issue: 
Fixes https://github.com/beautify-web/js-beautify/issues/2093
=> Fix Windows glob issue

web/onload.js
The logic for changing the theme was only invoked when using codemirror.
Fixes: #2133 
=> Fixed #2133 Theme Toggle on without_codemirror Mode

package-lock.json, package.json
=> Require nodejs v12 or greater

python/cssbeautifier/tests/__init__.py, python/jsbeautifier/tests/generated/__init__.py
Partial for #2152 - enables the jsbeautifier tests but css remains broken. 
=> Re-enable python javascript tests

index.html
=> fix: update SRI verification hash

README.md
Fixes Issue: #2199 
Updates `README.md` to document how to import the library with ESM import syntax.
=> Document importing js-beautify through ESM imports

index.html
In light of recent `polyfill[.]io` supply chain attack, this PR ensures Cloudflare's alternative CDN is used, instead of the malicious `polyfill.io`.
=> Use Cloudflare Polyfill CDN instead of polyfill[.]io
